### ISSUE TITLE
handling the phpcbf event returned with error code 255

### ISSUE THREAD

**Issue by hgodinho** [htmlburger/carbon-fields#1030]
## Version

  - Carbon Fields: 3.3
  - WordPress: 5.8
  - PHP: 7.4.22

## Problem
The error occurs when run `phpcbf` command at any php file.

## Error stack trace

```
$ composer run phpcbf classes
> php vendor/squizlabs/php_codesniffer/bin/phpcbf --standard=WordPress "classes"

Fatal error: Uncaught Error: Call to undefined function Carbon_Fields\Provider\add_filter() in C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php:254
Stack trace:
#0 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php(21): Carbon_Fields\Provider\Container_Condition_Provider->install_container_conditions(Object(Carbon_Fields\Pimple\Container))
#1 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Pimple\Container.php(274): Carbon_Fields\Provider\Container_Condition_Provider->register(Object(Carbon_Fields\Pimple\Container))
#2 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(385): Carbon_Fields\Pimple\Container->register(Object(Carbon_Fields\Provider\Container_Condition_Provider))
#3 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(69): Carbon_Fields\Carbon_Fields::get_default_ioc()
#4 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(60): Carbon_Fields\Carbon_Fields->__construct()
#5 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(164): Carbon_Fields\Carbon_Fields::instance()
#6 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-field-number\field.php(9): Carbon_Fields\Carbon_Fields::extend('Carbon_Field_Nu...', Object(Closure))      
#7 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\composer\autoload_real.php(71): require('C:\\Users\\55119\\...')
#8 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\composer\autoload_real.php(61): composerRequire211371e34294ed6b642cad8f9f07ce84('6632f90381dd49c...', 'C:\\Users\\55119\\...')
#9 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\autoload.php(7): ComposerAutoloaderInit211371e34294ed6b642cad8f9f07ce84::getLoader()
#10 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\squizlabs\php_codesniffer\autoload.php(79): include('C:\\Users\\55119\\...')
#11 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\squizlabs\php_codesniffer\bin\phpcbf(17): PHP_CodeSniffer\Autoload::load('PHP_CodeSniffer...')
#12 {main}
  thrown in C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php on line 254
PHP Fatal error:  Uncaught Error: Call to undefined function Carbon_Fields\Provider\add_filter() in C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php:254
Stack trace:
#0 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php(21): Carbon_Fields\Provider\Container_Condition_Provider->install_container_conditions(Object(Carbon_Fields\Pimple\Container))
#1 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Pimple\Container.php(274): Carbon_Fields\Provider\Container_Condition_Provider->register(Object(Carbon_Fields\Pimple\Container))
#2 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(385): Carbon_Fields\Pimple\Container->register(Object(Carbon_Fields\Provider\Container_Condition_Provider))
#3 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(69): Carbon_Fields\Carbon_Fields::get_default_ioc()
#4 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(60): Carbon_Fields\Carbon_Fields->__construct()
#5 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Carbon_Fields.php(164): Carbon_Fields\Carbon_Fields::instance()
#6 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-field-number\field.php(9): Carbon_Fields\Carbon_Fields::extend('Carbon_Field_Nu...', Object(Closure))      
#7 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\composer\autoload_real.php(71): require('C:\\Users\\55119\\...')
#8 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\composer\autoload_real.php(61): composerRequire211371e34294ed6b642cad8f9f07ce84('6632f90381dd49c...', 'C:\\Users\\55119\\...')
#9 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\autoload.php(7): ComposerAutoloaderInit211371e34294ed6b642cad8f9f07ce84::getLoader()
#10 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\squizlabs\php_codesniffer\autoload.php(79): include('C:\\Users\\55119\\...')
#11 C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\squizlabs\php_codesniffer\bin\phpcbf(17): PHP_CodeSniffer\Autoload::load('PHP_CodeSniffer...')
#12 {main}
  thrown in C:\Users\55119\[drive] hgod.in\Freelas\CREN\site\cren-tema\vendor\htmlburger\carbon-fields\core\Provider\Container_Condition_Provider.php on line 254
Script php vendor/squizlabs/php_codesniffer/bin/phpcbf --standard=WordPress handling the phpcbf event returned with error code 255
```

## Steps to Reproduce the Problem

  1. run `phpcbf` or `phpcs` at any php file.

**Comment by hgodinho** [comment]
actually is an issue with the [number-fields](https://github.com/htmlburger/carbon-field-number)
