### ISSUE TITLE
Appearance > Widgets will not load with a Carbon Fields widget defined

### ISSUE THREAD

**Issue by clubdeuce** [htmlburger/carbon-fields#996]
## Version

  - Carbon Fields: 3.3.2
  - WordPress: 5.7.1
  - PHP: 7.3

## Expected Behavior
I expect the Widgets page to load

## Actual Behavior
The widgets page will not load :
<img width="2476" alt="Screen Shot 2021-04-26 at 11 56 36 AM" src="https://user-images.githubusercontent.com/2600497/116113396-76916280-a686-11eb-8273-fba85a9ab538.png">

## Container definition
```php
<class-flyout-widget.php>
<?php
namespace ASPPB;

use Carbon_Fields\Field;
use Carbon_Fields\Widget;

/**
 * Class Flyout_Widget
 * @package ASPPB
 */
class Flyout_Widget extends Widget {

	/**
	 * Flyout_Widget constructor.
	 */
	public function __construct() {

		$this->setup( 'asppb_flyout_widget', __( 'Flyout Widget', 'asppb' ), __( 'Custom Widget for ASPPB', 'asppb' ), array(
			Field::make_image( 'top_icon', __( 'Top Icon', 'asppb' ) ),
			Field::make_text( 'widget_text', __( 'Widget Text', 'asppb' ) ),
			Field::make_image( 'widget_image', __( 'Widget Image', 'asppb' ) ),
			Field::make_text( 'button_text', __( 'Button Texgt', 'asppb' ) ),
			Field::make_text( 'button_url', __( 'Button URL', 'asppb' ) ),
		));

	}

	/**
	 * @param array $args
	 * @param array $instance
	 */
	public function front_end( $args, $instance ) {

		$instance = wp_parse_args( $instance, array(
			'icon_url'     => null,
			'widget_text'  => null,
			'widget_image' => null,
			'button_text'  => null,
			'button_link'  => null,
		) );

		$icon_html     = wp_get_attachment_image( $instance['top_icon'], 'full' );
		$widget_text   = $instance['widget_text'];
		$image_html    = wp_get_attachment_image( $instance['widget_image'], 'full' );
		$button_text   = $instance['button_text'];
		$button_link   = $instance['button_link'];

		require get_stylesheet_directory() . '/template-parts/flyout-widget.php';

	}

}

<functions.php>
/**
 * Register widget area.
 *
 * @link https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar
 */
function asppb_widgets_init() {
	register_widget( '\ASPPB\Flyout_Widget' );
}
add_action( 'widgets_init', 'asppb_widgets_init' );
```

## Steps to Reproduce the Problem

  1. Register widget
  1. Load `Appearance` -> ` Widgets`

##  Comments

web server error log:

```log
PHP Fatal error: Uncaught Error: Call to a member function import_storage() on null in /nas/content/live/asppbdev/wp-content/vendor/htmlburger/carbon-fields/core/Widget/Widget.php:128\nStack trace:\n#0 /nas/content/live/asppbdev/wp-includes/class-wp-widget.php(519): Carbon_Fields\\Widget\\Widget->form(Array)\n#1 /nas/content/live/asppbdev/wp-admin/includes/widgets.php(274): WP_Widget->form_callback(Array)\n#2 /nas/content/live/asppbdev/wp-admin/includes/widgets.php(60): wp_widget_control(Array, Array)\n#3 /nas/content/live/asppbdev/wp-admin/widgets.php(452): wp_list_widgets()\n#4 {main}\n thrown in /nas/content/live/asppbdev/wp-content/vendor/htmlburger/carbon-fields/core/Widget/Widget.php on line 128, referer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by jorostoyanov** [comment]
You should be using `add_action( 'widgets_init', '\ASPPB\asppb_widgets_init' );` since the function `asppb_widgets_init` is declared in the `ASPPB` namespace

**Comment by clubdeuce** [comment]
> You should be using `add_action( 'widgets_init', '\ASPPB\asppb_widgets_init' );` since the function `asppb_widgets_init` is declared in the `ASPPB` namespace

Yes, that was an error on my part in copying/pasting the code. The `add_action` function above is in a non-namespaced file. So, that is not the cause of this error.

**Comment by jorostoyanov** [comment]
I've just tested it with and without the namespace and it works fine on a clean install.

It seems non-connected to Carbon Fields

**Comment by clubdeuce** [comment]
@jorostoyanov  The only plugin that is active on the site is the `ManageWP Worker`. Are you aware of any issues with that specific plugin?

**Comment by clubdeuce** [comment]
@jorostoyanov And with the `ManageWP` plugin deactivated, it still has the same issue. This is on WPEngine hosting.

**Comment by clubdeuce** [comment]
solved by using :

```php
use Carbon_Fields\Widget\Widget;
```
